### ISSUE TITLE
hola

### ISSUE THREAD

**Issue by bucaran** [bakiro/sivae#1]
@bakiro Hola, por esto proyecto, imagino que también eres Venezolano. Saludos.

Quería contactarte por twitter or email pero como no tienes contacto, te envío por aquí.

Estás usando oh-my-fish? Yo ya no mantengo ese proyecto, ahora el plugin manager de fish es fisherman: https://github.com/fisherman/fisherman, te agradezco que te unas al proyecto y si tienes dudas o algo me haces un ping y te respondo de inmediato.

✌️

**Comment by bucaran** [comment]
@bakiro

**Comment by bucaran** [comment]
@bakiro

**Comment by bucaran** [comment]
@bakiro

**Comment by bucaran** [comment]
@bakiro

**Comment by bucaran** [comment]
@bakiro

**Comment by bakiro** [comment]
Gracias Jorge, es correcto, soy Venezolano, ya actualice el perfil, voy a utilizar tu desarrollo y te cuento como va ;), saludos y gracias por contactar

**Comment by bucaran** [comment]
Epa @bakiro, ya veo! :) Gracias! Sí, cualquier cosa avísame por favor o únete al chat si usas slack <http://join.fisherman.sh>.
